# Generated by Django 4.0.5 on 2022-07-21 16:54

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Заголовок')),
                ('text', models.TextField(blank=True, verbose_name='Текст статьи')),
                ('foto', models.ImageField(upload_to='photos/%Y/%m/%d', verbose_name='Фото')),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Время создания')),
                ('published_date', models.DateTimeField(blank=True, null=True, verbose_name='Время публикации')),
            ],
            options={
                'verbose_name': 'Герои',
                'verbose_name_plural': 'Герои',
                'ordering': ['created_date', 'title'],
            },
        ),
    ]
