# Generated by Django 4.0.5 on 2022-07-21 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_usersad'),
    ]

    operations = [
        migrations.CreateModel(
            name='MyUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=25, verbose_name='Ник')),
                ('birthday', models.DateField(blank=True, null=True, verbose_name='Дата рождения')),
                ('date_joined', models.DateTimeField(blank=True, max_length=30, verbose_name='Дата присоединения')),
                ('email', models.EmailField(max_length=40, verbose_name='Адрес элктронной почты')),
                ('first_name', models.CharField(max_length=20, verbose_name='Имя')),
                ('last_name', models.CharField(max_length=20, verbose_name='Фамилия')),
            ],
        ),
        migrations.DeleteModel(
            name='UsersAd',
        ),
    ]
