# Generated by Django 4.0.5 on 2022-07-21 16:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_myuser_delete_usersad'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MyUser',
        ),
    ]
